CREATE TABLE [dbo].Announcements
(
	AnnouncementId INT NOT NULL IDENTITY(1, 1) CONSTRAINT PK_Announcements PRIMARY KEY,
	Title VARCHAR(255) NOT NULL,
	Content NVARCHAR(4000) NOT NULL,
	AuthorId VARCHAR(255) NOT NULL CONSTRAINT FK_Announcemenets_AuthorId REFERENCES dbo.Players (PlayerId),
	LastUpdate DATETIME2 NOT NULL CONSTRAINT DF_Announcements_LastUpdate DEFAULT (SYSDATETIME()),
    CreateDate DATETIME2 NOT NULL CONSTRAINT DF_Announcements_CreateDate DEFAULT (SYSDATETIME())
)
