CREATE TABLE PlayerBans 
(
	BanId INT IDENTITY(1, 1) NOT NULL CONSTRAINT PK_PlayerBans PRIMARY KEY,
	PlayerId VARCHAR(255) NOT NULL CONSTRAINT FK_PlayerBans_PlayerId REFERENCES dbo.Players (PlayerId),
	PunisherId VARCHAR(255) NOT NULL CONSTRAINT FK_PlayerBans_PunisherId REFERENCES dbo.Players (PlayerId),
	Reason NVARCHAR(1000) NOT NULL,
	ExpiryDate DATETIME2(0) NULL,
	CreateDate DATETIME2(0) NOT NULL CONSTRAINT DF_PlayerBans_CreateDate DEFAULT (SYSDATETIME())
);