CREATE TABLE dbo.Products (
	ProductId SMALLINT IDENTITY(1,1) NOT NULL CONSTRAINT PK_Products PRIMARY KEY,
	ShortName VARCHAR(50) NOT NULL,
	Name NVARCHAR(255) NOT NULL,
	Description NVARCHAR(2000) NOT NULL,
	Price DECIMAL(9,2) NOT NULL,
	RankId SMALLINT NULL CONSTRAINT FK_Products_RankId REFERENCES dbo.Ranks (RankId),
	Coins DECIMAL(9,2) NOT NULL CONSTRAINT DF_Products_Coins DEFAULT (0),
	Category AS CAST(CASE WHEN RankId IS NULL THEN 'COINS' WHEN Coins = 0 THEN 'RANKS' ELSE 'BUNDLE' END AS VARCHAR(128)), 
	CreateDate DATETIME2(0) NOT NULL CONSTRAINT DF_Products_CreateDate DEFAULT SYSDATETIME(),
	ActiveFlag BIT NOT NULL CONSTRAINT DF_Products_ActiveFlag DEFAULT (1)
);