CREATE TABLE dbo.Products
(
	ProductId INT IDENTITY(1, 1) NOT NULL,
	Name VARCHAR(30) NOT NULL,
	Description VARCHAR(4000) NOT NULL,
	Image VARBINARY(MAX) NOT NULL,
	Price DECIMAL(9, 2) NOT NULL,
	Category VARCHAR(30) NOT NULL,
	Duration INT DEFAULT(NULL) NULL,
	UpdateDate DATETIME2 NOT NULL DEFAULT(SYSDATETIME()),
	CreateDate DATETIME2 NOT NULL DEFAULT(SYSDATETIME())
);