CREATE TABLE dbo.Products
(
	ProductId INT IDENTITY(1, 1) NOT NULL CONSTRAINT PK_Products PRIMARY KEY,
	Label VARCHAR(30) NOT NULL,
	Details NVARCHAR(4000) NOT NULL,
	Picture VARBINARY(MAX) NOT NULL,
	Price DECIMAL(9, 2) NOT NULL,
	Category VARCHAR(30) NOT NULL,
	Duration INT NULL,
	Visible BIT NOT NULL CONSTRAINT DF_Products_Visible DEFAULT(0),
	LastUpdate DATETIME2 NOT NULL CONSTRAINT DF_Products_LastUpdate DEFAULT(SYSDATETIME()),
	CreateDate DATETIME2 NOT NULL CONSTRAINT DF_Products_CreateDate DEFAULT(SYSDATETIME())
);